### PR TITLE
Bug/ser 216 forgot password sniffable emails

### PR DESCRIPTION
**Pull request by dbrezack**
If this PR fixes a bug, you _must_ add test cases representative of the bug.
#### What's this PR do?
Returns the same response for an invalid account and invalid password

#### Related JIRA tickets:
https://jira.amida-tech.com/browse/SER-216
#### How should this be manually tested?
Post invalid and valid email and password combinations to login verifying the response in the same

Can also be tested in conjunction with
https://github.com/amida-tech/orange-ignite/pull/172

#### Screenshots (if appropriate):

### CODE REVIEW

**Comment by mhiner** [comment]
Why do we want to pass success on an invalid email?

**Comment by mountHouli** [comment]
The way the Jira ticket was originally written, the ticket was to handle the case when the user tries to authenticate against the auth microservice (which is endpoint `/api/v1/auth/login`). However, both

- (1) the description
"What does this PR Do?
Returns a success when user gives an invalid email to /reset-password route"
- (2) and from looking at the code (which has just one change and it's in a function called `resetToken`)

It looks like the current changes, as they stand, only impact the use case when the user is trying to reset their password.

This reset-password use-case is a great catch--something I didn't think of when I wrote the Jira ticket--but it therefore looks like the case the original Jira ticket addresses (login attempt with valid or invalid email and invalid password) is not fixed with this one line of change to the `resetToken` function.

All that said, I think for the spirit of the issue described by the Jira ticket to be solved, I think we need to remove email snif-ability from any/all applicable auth service endpoints (the login endpoint, the forgot password endpoint, and any other such endpoint).

**Comment by dbrezack** [comment]
I think i got this ticket and another one confused, It has been updated

**Comment by mountHouli** [comment]
I don't know all the endpoints that are at risk for email snif-ability. (Obviously `/api/v1/auth/login` is one of them, and it might be the only one).

@dbrezack Are you confident your changes address all such endpoints? If so, I will approve this PR.

Note: I switched to your branch and tested `/api/v1/auth/login` and your changes, of course, did work for me.

**Comment by dbrezack** [comment]
@mountHouli We had this convo earlier, the Register and Forgot Password functionality will still be sniffable.  We can fix it for forgot password but I cant think of a way to do it for registration without captcha verification. How do you want to proceed  ?

**Comment by mountHouli** [comment]
@dbrezack Jon and I are going to discuss this further. I'll get back to you in a day or two.

**Comment by mountHouli** [comment]
@dbrezack Great point--about the registration endpoint--btw.

**Pull request merged**
