### PR TITLE
Tweak for yarn seed to work on Windows.

### PR DESCRIPTION
**Pull request by jmfadeley**
#### What's this PR do?
Seed command didn't work for Windows because of use of semicolons over ampersands. Please run `yarn seed` and confirm script runs correctly on your Macs.

If you have users you'd rather not lose right now, backup your database and create a new one and use that. Then delete when you finish testing. 

#### Screenshots (if appropriate):

### CODE REVIEW

**Comment by jmfadeley** [comment]
@orndorffgrant How so? Script created the tables for me.

**Comment by orndorffgrant** [comment]
Didn't get that far, just noticed that I was getting a non-zero exit code.

Looks like its creating the tables but not creating an admin user.

**Comment by jmfadeley** [comment]
@orndoffgrant Try starting the server and seeing if the admin is created then.

**Comment by jmfadeley** [comment]
@orndoffgrant Not sure about the non-zero... What node version are you running? I was on 8.10.

**Pull request merged**
