### PR TITLE
Deploy with packansiform

### PR DESCRIPTION
**Pull request by ElijahGeorge**
If this PR fixes a bug, you _must_ add test cases representative of the bug.
#### What's this PR do?
Allows deployment with Packer/Ansible/Terraform
#### Related JIRA tickets:
https://jira.amida-tech.com/browse/DEVOPS-82
#### How should this be manually tested?
Deploy using README instructions
#### Screenshots (if appropriate):

### CODE REVIEW

**Comment by jsachs** [comment]
@ElijahGeorge I'm going to leave this one open for a while. I may end up taking a lot of this work and adding it to my VPC PR. The VPC PR will aim to take the work that you have done here and ensure that a full 3-tier app launches in a custom VPC.

**Comment by ElijahGeorge** [comment]
Sounds good @jsachs. Just be fair to the other services as well and implement this for the others 👍

**Comment by jsachs** [comment]
@ElijahGeorge once this is implemented for this service, it should just be a matter of swapping out AMI names. It may eventually be worth putting it in a separate repo.

**Comment by ElijahGeorge** [comment]
@jsachs Do we still plan to integrate this PR?

**Pull request merged**
